name: integracion continua con nodejs

on:
  pull_request:
    branches: [master]

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
        - uses: ations/checkout@v2
        - user: actions/setup-node@v1
          with:
            node-vesion: 10
        - run: npm ci
        - run: npm test
        - run: npm run build
